version: "1.0"

volumes:
  api_gateway_data:
  api_gateway_gradle_data:

networks:
  api_gateway_net:
    name: "api_gateway_net"

services:
  api_gateway:
    container_name: "api-gateway"
    build:
      dockerfile: ./docker/Dockerfile
      context: ..
    ports:
      - ${API_GATEWAY_HOST_PORT}:${API_GATEWAY_CONTAINER_PORT}
    volumes:
      - api_gateway_data:${API_GATEWAY_VOLUMES}
      - api_gateway_gradle_data:${API_GATEWAY_GRADLE_VOLUMES}
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - api_gateway_net
    environment:
      SERVER_PORT: ${SERVER_PORT}
      APPLICATION_NAME: ${APPLICATION_NAME}
      AUTH_COMMAND_SERVICE_ID: ${AUTH_COMMAND_SERVICE_ID}
      AUTH_COMMAND_SERVICE_URI: ${AUTH_COMMAND_SERVICE_URI}
      AUTH_COMMAND_SERVICE_METHOD: ${AUTH_COMMAND_SERVICE_METHOD}
      AUTH_COMMAND_SERVICE_PATH: ${AUTH_COMMAND_SERVICE_PATH}
      AUTH_QUERY_SERVICE_ID: ${AUTH_QUERY_SERVICE_ID}
      AUTH_QUERY_SERVICE_URI: ${AUTH_QUERY_SERVICE_URI}
      AUTH_QUERY_SERVICE_METHOD: ${AUTH_QUERY_SERVICE_METHOD}
      AUTH_QUERY_SERVICE_PATH: ${AUTH_QUERY_SERVICE_PATH}
      BUILDING_COMMAND_SERVICE_ID: ${BUILDING_COMMAND_SERVICE_ID}
      BUILDING_COMMAND_SERVICE_URI: ${BUILDING_COMMAND_SERVICE_URI}
      BUILDING_COMMAND_SERVICE_METHOD: ${BUILDING_COMMAND_SERVICE_METHOD}
      BUILDING_COMMAND_SERVICE_PATH: ${BUILDING_COMMAND_SERVICE_PATH}
      BUILDING_QUERY_SERVICE_ID: ${BUILDING_QUERY_SERVICE_ID}
      BUILDING_QUERY_SERVICE_URI: ${BUILDING_QUERY_SERVICE_URI}
      BUILDING_QUERY_SERVICE_METHOD: ${BUILDING_QUERY_SERVICE_METHOD}
      BUILDING_QUERY_SERVICE_PATH: ${BUILDING_QUERY_SERVICE_PATH}
      HUMAN_COMMAND_SERVICE_ID: ${HUMAN_COMMAND_SERVICE_ID}
      HUMAN_COMMAND_SERVICE_URI: ${HUMAN_COMMAND_SERVICE_URI}
      HUMAN_COMMAND_SERVICE_METHOD: ${HUMAN_COMMAND_SERVICE_METHOD}
      HUMAN_COMMAND_SERVICE_PATH: ${HUMAN_COMMAND_SERVICE_PATH}
      HUMAN_QUERY_SERVICE_ID: ${HUMAN_QUERY_SERVICE_ID}
      HUMAN_QUERY_SERVICE_URI: ${HUMAN_QUERY_SERVICE_URI}
      HUMAN_QUERY_SERVICE_METHOD: ${HUMAN_QUERY_SERVICE_METHOD}
      HUMAN_QUERY_SERVICE_PATH: ${HUMAN_QUERY_SERVICE_PATH}
      PAYMENT_COMMAND_SERVICE_ID: ${PAYMENT_COMMAND_SERVICE_ID}
      PAYMENT_COMMAND_SERVICE_URI: ${PAYMENT_COMMAND_SERVICE_URI}
      PAYMENT_COMMAND_SERVICE_METHOD: ${PAYMENT_COMMAND_SERVICE_METHOD}
      PAYMENT_COMMAND_SERVICE_PATH: ${PAYMENT_COMMAND_SERVICE_PATH}
      PAYMENT_QUERY_SERVICE_ID: ${PAYMENT_QUERY_SERVICE_ID}
      PAYMENT_QUERY_SERVICE_URI: ${PAYMENT_QUERY_SERVICE_URI}
      PAYMENT_QUERY_SERVICE_METHOD: ${PAYMENT_QUERY_SERVICE_METHOD}
      PAYMENT_QUERY_SERVICE_PATH: ${PAYMENT_QUERY_SERVICE_PATH}
      ACTIVITY_COMMAND_SERVICE_ID: ${ACTIVITY_COMMAND_SERVICE_ID}
      ACTIVITY_COMMAND_SERVICE_URI: ${ACTIVITY_COMMAND_SERVICE_URI}
      ACTIVITY_COMMAND_SERVICE_METHOD: ${ACTIVITY_COMMAND_SERVICE_METHOD}
      ACTIVITY_COMMAND_SERVICE_PATH: ${ACTIVITY_COMMAND_SERVICE_PATH}
      ACTIVITY_QUERY_SERVICE_ID: ${ACTIVITY_QUERY_SERVICE_ID}
      ACTIVITY_QUERY_SERVICE_URI: ${ACTIVITY_QUERY_SERVICE_URI}
      ACTIVITY_QUERY_SERVICE_METHOD: ${ACTIVITY_QUERY_SERVICE_METHOD}
      ACTIVITY_QUERY_SERVICE_PATH: ${ACTIVITY_QUERY_SERVICE_PATH}
      CORS_DOMAIN: ${CORS_DOMAIN}